backend:
  name: github
  repo: ieee-ihuthess/sb-website
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dk5dlrnv1
    api_key: 453579541597887

collections:
  - name: "members"
    label: "Member"
    folder: "content/members"
    create: true
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Designation"
        name: "designation"
        widget: "string"
        default: "Member"
      - label: "Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 250
              quality: auto
              crop: fill
      - label: "Social Links"
        name: "socialLinks"
        widget: "object"
        collapsed: true
        fields:
          - {
              label: "GitHub link",
              name: "github",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "GitLab link",
              name: "gitlab",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Facebook link",
              name: "facebook",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Instagram link",
              name: "instagram",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "LinkedIn link",
              name: "linkedin",
              widget: "string",
              required: false,
              default: "#",
            }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Event Title"
        name: "title"
        widget: "string"
      - label: "Event Description"
        name: "body"
        widget: "markdown"
      - label: "Event Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 320
              height: 180
              quality: auto
              crop: fill
      - label: "Event Date"
        name: "date"
        widget: "datetime"
      - label: "Event Photos"
        name: "photos"
        required: false
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - label: "Event Links"
        name: "links"
        widget: "object"
        collapsed: true
        fields:
          - {
              label: "YouTube Link",
              name: "youtube",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Facebook Link",
              name: "facebook",
              widget: "string",
              required: false,
              default: "#",
            }
          - {
              label: "Slides link",
              name: "slides",
              widget: "string",
              required: false,
              default: "#",
            }
      - label: "Registration Form"
        name: "registrationLink"
        widget: "string"
        required: false
        default: "#"
        hint: "If you want no link to appear, insert '#' as the value."
  - name: "faq"
    label: "Faq"
    folder: "content/faq"
    create: true
    slug: "{{question}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - {
          label: "Question Order",
          name: "order",
          value_type: "int",
          hint: "Order in which you want the question to appear in FAQ section",
        }
      - {
          label: "Language",
          name: "locale",
          widget: "select",
          options: [
            { label: "Greek", value: "el-gr"},
            { label: "English", value: "en-gb"}
          ]
        }
      - { label: "Answer", name: "body", widget: "markdown" }
  - name: "galleryImage"
    label: "Gallery Image"
    folder: "content/gallery"
    create: true
    slug: "{{caption}}-{{id}}"
    fields:
      - label: "Image"
        name: "image"
        widget: "image"
        config:
          default_transformations:
            - fetch_format: auto
              width: 1024
              height: 480
              quality: auto
              crop: fill
      - label: "Caption"
        name: "caption"
        widget: "string"
  - name: "blogPosts"
    label: "Blog Posts"
    folder: "content/blogposts"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "markdown"
      - label: "Created on"
        name: "date"
        widget: "datetime"
